import { Badge } from "@/components/ui/badge";
import { useParams } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { ArrowLeft, Calendar } from "lucide-react";
import { BLOG_POSTS } from "./BlogPage";

const FULL_CONTENT: Record<string, string[]> = {
  "mat-access-ohio": [
    "Northeast Ohio's Region 13 is home to more than 1.2 million people across seven counties, yet the number of buprenorphine-waivered providers has declined for three consecutive years. When a provider closes, patients have no real-time signal — they call numbers that go to voicemail, check websites last updated in 2022, and often give up before finding care. The gap between supply and demand isn't theoretical; it's measured in missed appointments, relapse events, and overdose deaths.",
    "Live Now Recovery was built to solve the information problem. By giving providers a simple, privacy-preserving toggle to mark their availability, we create the real-time layer that has never existed before. The 4-hour decay rule means stale data is never presented as active — if a provider hasn't confirmed their status in 4 hours, their pin turns yellow and their status reads Unknown, protecting patients from false hope.",
    "Our Proof of Presence system adds a community-powered layer. Peer specialists and volunteers on the ground can generate one-time QR codes tied to a ZIP code. When scanned at a verified provider location, the system anonymously increments the presence count for that ZIP — giving policymakers and advocates real data about where care is actually happening.",
    "The data is not a solution in itself. The solution requires more providers, better reimbursement, less stigma, and systemic change. But you can't fix what you can't see. Live Now Recovery makes the invisible visible — for patients in crisis, for advocates driving policy, and for anyone fighting to close the MAT access gap in Region 13.",
  ],
  "cost-plus-drugs-suboxone": [
    "Buprenorphine/naloxone 8mg/2mg film — the generic version of Suboxone — costs approximately $185 per month at most retail pharmacies. That price, for a medication that is the clinical standard of care for opioid use disorder, creates a $2,220 annual barrier to recovery. For someone rebuilding their life on a fixed income or minimum wage, that number can be the difference between staying in treatment and dropping out entirely.",
    "Mark Cuban Cost Plus Drugs offers the same medication — 60 films of generic buprenorphine/naloxone 8mg/2mg, a 30-day supply — for $45.37 per month. The savings are $139.63 per month, or $1,675 per year. MCCPD's NCPDP ID is 5755167. Any prescriber can call that in, and any patient can initiate a prescription transfer through the Cost Plus Drugs website at costplusdrugs.com.",
    "The transfer process is straightforward. Call your prescriber and ask them to send the prescription to Mark Cuban Cost Plus Drugs, NCPDP 5755167. Alternatively, use the Cost Plus Drugs website to initiate the transfer directly. Medications ship in discreet packaging within two to three business days with free standard shipping, and same-day processing is available in most cases.",
    "Live Now Recovery includes the Cost Plus price bridge on every provider page because it's a clinical obligation, not a marketing feature. If a provider is sending patients to a pharmacy where they'll pay $185 instead of $45, and no one told them a cheaper option existed, that's a systemic failure. Price transparency is a public health intervention — and it's one of the simplest, highest-impact changes any provider can make today.",
  ],
  "peer-recovery-proof-of-presence": [
    "Peer recovery specialists occupy a unique position in the MAT ecosystem — they have the trust that clinical systems often don't, and the community presence that institutional settings frequently miss. They meet people at emergency rooms, at sober houses, in parking lots outside treatment centers, and at kitchen tables. They know which providers are actually open and actively serving patients before any database does.",
    "The Proof of Presence (PoP) system was designed specifically for this community. A peer specialist can open Live Now Recovery, enter the ZIP code of the location where they're helping someone access care, and generate a one-time QR code valid for five minutes — long enough for a quick scan, short enough to prevent replay abuse. The entire interaction takes less than 30 seconds and requires no account, no login, and no personal information.",
    "When that QR code is scanned at the provider location, the system records a single anonymous presence count for that ZIP. No names. No clinic record numbers. No PHI of any kind. Just a signal: someone was here, in this ZIP, at this time. Aggregated across hundreds of interactions, those counts tell a story about where care is actually happening versus where it is theoretically available.",
    "Several NE Ohio peer recovery organizations are currently piloting PoP in the field. Early data shows presence clusters in Cuyahoga, Lorain, and Summit counties that match anecdotal reports from peer specialists about which providers are actively serving patients. The invisible is becoming visible — and that visibility is the first step toward directing resources, advocacy, and policy to the places where they're most needed.",
  ],
  "buprenorphine-vs-methadone": [
    "Buprenorphine and methadone are both FDA-approved, evidence-based, gold-standard treatments for opioid use disorder — but they work differently, fit different patients, and carry very different access logistics. Understanding the distinction is not about ranking one above the other; it's about matching the right treatment to the right person at the right stage of their recovery journey.",
    "Methadone is a full opioid agonist dispensed daily at federally licensed opioid treatment programs (OTPs). Its long half-life provides stable blood levels that eliminate cravings and prevent withdrawal throughout the day. For patients with severe, long-duration opioid dependence or those who have relapsed on buprenorphine, methadone's stronger receptor binding can provide the stability needed to re-engage with daily life. The trade-off is logistics: patients must present in person daily, often for months, before earning take-home doses. For people without reliable transportation or childcare, this structure is a significant barrier.",
    "Buprenorphine is a partial agonist with a ceiling effect on respiratory depression, making it significantly safer in overdose. It can be prescribed by any qualifying physician, nurse practitioner, or physician assistant and dispensed at a regular pharmacy — meaning patients can fill monthly prescriptions and take their medication at home. Since the federal government removed the X-waiver requirement in 2023, the number of prescribers who can offer buprenorphine has expanded significantly, improving access in rural and underserved areas where OTPs don't exist.",
    "The clinical evidence does not support a hierarchy between these medications. Both reduce illicit opioid use, reduce overdose mortality, improve treatment retention, and lower rates of infectious disease transmission. Patient preference, prior treatment history, social circumstances, and geographic access to OTPs are the primary factors that should guide the choice. A person who has tried buprenorphine and relapsed may do better with the structure of methadone. A person in a rural county with no OTP within 60 miles may only have access to buprenorphine. Both options deserve full clinical support, and no patient should be stigmatized for choosing either.",
  ],
  "naloxone-access-ohio": [
    "Ohio has operated a statewide standing order for naloxone since 2015, meaning any licensed Ohio pharmacist can dispense naloxone — under any of its brand names (Narcan, Kloxxado, Revive) or as a generic — without a personal prescription from a physician. In theory, this makes naloxone universally accessible to any Ohioan who walks into a pharmacy. In practice, access is uneven in ways that directly correlate with overdose mortality rates.",
    "The gaps are geographic, economic, and structural. Rural pharmacies frequently don't stock naloxone or require special ordering. In lower-income urban neighborhoods, some pharmacies do stock it but chain pharmacy staff are inconsistently trained on the standing order, leading to unnecessary refusals. The nasal spray formulation (Narcan) is the most commonly stocked option and requires no training to use, but its retail price of $20–$50 for a two-dose kit remains a barrier for people with no insurance and no cash.",
    "Community-based distribution programs fill many of the gaps that pharmacies miss. Harm reduction organizations, some county health departments, and certified peer recovery supporters can distribute naloxone under Project DAWN (Deaths Avoided With Naloxone), Ohio's statewide overdose education and naloxone distribution program. Live Now Recovery maps Narcan distribution sites alongside MAT providers so people can find both resources in a single search, reducing the time between need and access.",
    "Carrying naloxone does not enable drug use — it enables survival. Every person in recovery, every family member, every peer specialist, and every first responder who carries naloxone is extending the window of time in which someone can get help. The research is unambiguous: community-level naloxone distribution reduces overdose mortality without increasing drug use. Closing the distribution gap in Ohio's Region 13 is one of the fastest, cheapest interventions available to policymakers today.",
  ],
  "stigma-killing-people": [
    "The clinical evidence on medication-assisted treatment is unambiguous. Buprenorphine reduces overdose mortality by 50–75% in patients who remain on it. Methadone reduces illicit opioid use by 40–60% and cuts overdose death rates by more than half. Both medications improve treatment retention, reduce HIV and hepatitis C transmission, and lower rates of criminal justice involvement. The science is not a matter of debate. The barrier to treatment isn't clinical — it's cultural.",
    "Stigma against MAT is pervasive and often institutionalized. Studies show that a majority of residential treatment programs in the US either refuse to admit patients on MAT or require them to taper off as a condition of entry — despite SAMHSA guidelines explicitly condemning this practice. Judges in drug court systems have historically required abstinence from MAT as a condition of program participation. Family members, employers, and faith communities routinely pressure people in recovery to stop their medication because they believe it means the person is 'still using.' None of these positions have clinical support.",
    "The criminalization of addiction has deepened the stigma problem. Decades of enforcement-first drug policy created a cultural association between addiction and moral failure that clinical language has struggled to displace. The shift in terminology from 'addict' to 'person with a substance use disorder' is meaningful but insufficient on its own. The structural reinforcement — insurance reimbursement disparities, lack of MAT in jails and prisons, inadequate prescriber training — reflects a system that still treats opioid use disorder as a character flaw rather than a chronic medical condition.",
    "The antidote to stigma is not persuasion alone — it's outcomes. When people see their neighbors, coworkers, and family members stabilize on MAT, return to work, reconnect with their children, and rebuild their lives over years and decades, the cultural narrative changes. Live Now Recovery exists to make those outcomes possible by closing the information gap that prevents people from getting started. You cannot experience the benefits of a treatment you cannot find.",
  ],
  "fentanyl-third-wave": [
    "Ohio's opioid crisis has moved in three distinct waves, each more lethal than the last. The first wave began in the late 1990s when pharmaceutical manufacturers aggressively marketed opioid painkillers as safe and non-addictive, and prescribing rates in Ohio — particularly in the Appalachian southeast and the industrial northeast — soared. By the mid-2000s, Ohio had among the highest opioid prescribing rates in the country, and prescription pill addiction was widespread across demographics that had no prior drug use history.",
    "The second wave arrived when prescription supply was tightened through prescriber limits and drug monitoring programs. People dependent on pills shifted to heroin, which was cheaper, widely available, and offered through the same distribution networks that had supplied the pill market. Ohio heroin deaths spiked dramatically between 2010 and 2015. The overdose profile changed: deaths were now concentrated among younger adults, in urban and suburban areas, and the overdoses were faster-onset and harder to reverse than pill-era deaths.",
    "The third wave — fentanyl — arrived around 2016 and has never receded. Illicitly manufactured fentanyl is 50 to 100 times more potent than morphine by weight. A lethal dose is measured in micrograms. It has largely displaced heroin in the Ohio street drug supply, and it now contaminates not just opioid supplies but stimulants, benzodiazepines, and counterfeit pills. A person who used heroin in 2013 and relapses in 2026 is encountering an entirely different drug supply — one where their prior tolerance is irrelevant and the margin for error is effectively zero.",
    "Fentanyl has fundamentally changed the MAT landscape. The case for continuous, uninterrupted buprenorphine or methadone therapy is stronger than it has ever been, because the alternative — any period of abstinence followed by relapse — now carries near-zero tolerance and a dramatically elevated overdose risk. Naloxone availability is more critical because fentanyl overdoses are faster and may require multiple doses to reverse. And the infrastructure problem Live Now Recovery is addressing — real-time visibility into which providers are available right now — is more urgent in a fentanyl era where time from crisis to treatment is measured in hours, not days.",
  ],
  "warm-handoff-saves-lives": [
    "A phone number is not a referral. Giving someone in crisis a list of treatment center phone numbers is not a warm handoff — it's a bureaucratic gesture that research shows leads to treatment uptake rates of 10–20%. A warm handoff is a direct, real-time human connection: a peer specialist or care coordinator places a call, reaches a live person at the receiving provider, and either transfers the patient directly or confirms an appointment while the patient is still in the room. Treatment uptake rates for warm handoffs consistently exceed 60% in published literature.",
    "The mechanism of failure in phone referrals is well understood. People in active addiction — or in the acute aftermath of an overdose — are in a physiological state that makes future-oriented planning neurologically difficult. The executive function required to call a number, navigate a phone tree, schedule an appointment, manage transportation, and follow through three days later is exactly the capacity that opioid use disorder impairs. Asking someone in that state to complete a multi-step administrative process on their own is a design failure, not a patient failure.",
    "In NE Ohio, the warm handoff model has been implemented most successfully in emergency department settings. ADAMHS Board of Cuyahoga County funds peer recovery specialists stationed at University Hospitals and MetroHealth who can initiate buprenorphine in the ED and complete warm handoffs to outpatient MAT providers before discharge. The data from these programs shows dramatic reductions in 30-day return visits and significant increases in 30-day treatment retention compared to standard discharge-with-referral protocols.",
    "Live Now Recovery is built to support warm handoffs by solving the information bottleneck that peer specialists hit when they try to connect someone to care. When a peer specialist needs to know which buprenorphine prescriber in Cuyahoga County has availability right now — not last week's directory, not a website that hasn't been updated — they need real-time data. The Live Toggle system exists to give peer specialists the signal they need to complete handoffs faster and with more confidence that the patient will actually reach care.",
  ],
  "recovery-housing-ohio": [
    "Recovery housing — sometimes called sober living, recovery residences, or Oxford Houses — is structured, substance-free communal living for people in recovery from addiction. Unlike inpatient treatment, recovery housing is not a clinical setting; it's a housing solution that provides accountability, peer support, and stability during the period of early recovery when relapse risk is highest. The evidence on recovery housing is consistent: residents who stay 90 days or longer have significantly better long-term sobriety outcomes, higher employment rates, and lower criminal justice involvement than those who do not access stable housing in early recovery.",
    "In Northeast Ohio, recovery housing ranges from highly structured Level III and IV Oxford Houses and MASH-certified residences to less formal peer-run Level I and II homes. MASH certification (Ohio's recovery housing certification program) provides accountability standards around house rules, peer governance, and resident rights. ADAMHS Board of Cuyahoga County, Summit County ADM, and several faith-based networks operate or fund recovery housing in the region, and some homes now specifically serve people on MAT — an important development given the historic exclusion of MAT users from many abstinence-only programs.",
    "One of the most common concerns for people seeking recovery housing while on buprenorphine or methadone is whether they will be required to stop their medication as a condition of residency. Many traditional sober living programs have historically maintained abstinence-only policies that treated MAT as equivalent to illicit use. That position is not supported by clinical evidence and is increasingly challenged by SAMHSA guidance and state-level policy. In Ohio, several MASH-certified programs now explicitly welcome residents on MAT, and the list is growing. If a program tells you to discontinue your medication as a condition of entry, that program is not following best practices.",
    "The connection between stable housing and recovery outcomes is not optional — it's foundational. Unstable housing is one of the strongest predictors of treatment dropout and relapse. When someone leaves a treatment program and has no safe place to sleep, no structure, and no community of accountability, the likelihood of sustained recovery drops dramatically regardless of the quality of the clinical care they received. Closing the MAT access gap and closing the recovery housing gap are inseparable goals. Live Now Recovery links to housing resources in every city guide because access to a bed is as urgent as access to a prescription.",
  ],
  "samhsa-guidelines-mat": [
    "In January 2023, the federal government eliminated the DATA 2000 waiver — commonly called the X-waiver — as a condition for prescribing buprenorphine for opioid use disorder. For more than two decades, any physician, nurse practitioner, or physician assistant who wanted to prescribe buprenorphine was required to complete eight hours of specialized training, register with the DEA, and obtain a separate waiver. The requirement created a significant bureaucratic barrier that limited prescriber supply, particularly in rural areas and primary care settings. Its elimination was one of the most consequential MAT policy changes in the history of the epidemic.",
    "SAMHSA's current guidelines on MAT reflect the best available evidence and the accumulated clinical consensus of two decades of research. The guidelines affirm that buprenorphine, methadone, and naltrexone are all evidence-based treatments for opioid use disorder, that there is no maximum recommended duration of treatment (i.e., patients should remain on medication as long as it is beneficial, which for many people means years to lifetime), and that abrupt discontinuation of MAT is associated with dramatically elevated overdose mortality risk. SAMHSA explicitly condemns policies that require patients to demonstrate abstinence before initiating MAT, or that require tapering as a condition of program participation.",
    "For Ohio patients, the X-waiver removal means that your primary care physician — the doctor who manages your blood pressure and diabetes — can now prescribe buprenorphine without any special certification if they choose to do so. This is a significant expansion of potential prescriber supply that has not yet been fully realized. Many primary care providers remain unfamiliar with buprenorphine or uncomfortable prescribing it due to training gaps, stigma, or concerns about DEA scrutiny. Patient advocacy and provider education are critical to translating the regulatory change into actual expanded access.",
    "The practical implications for patients in Ohio's Region 13 are still unfolding. The number of active buprenorphine prescribers has increased since the X-waiver was removed, but not as dramatically as policy advocates had hoped. Structural barriers — inadequate reimbursement, insufficient training, lingering stigma in primary care settings, and the administrative burden of treating patients with SUD — remain. Live Now Recovery tracks which providers are actively prescribing and accepting new patients so that patients and peer specialists can identify real, available options rather than theoretical ones.",
  ],
  "anonymous-technology-privacy": [
    "Surveillance fear is real, rational, and clinically significant. Research consistently shows that fear of stigma, employment consequences, custody loss, and criminal justice involvement prevents people with opioid use disorder from seeking help. When someone searches online for addiction treatment, that search can become part of their digital profile, shared with data brokers, surfaced in background checks, or used to target them with intrusive advertising. The decision to seek help should not create a permanent digital record that follows someone for years. Live Now Recovery was built on the premise that the architecture of the tool is a clinical decision.",
    "The technical approach is straightforward. Live Now Recovery does not require patient accounts. Patients cannot create accounts even if they wanted to — the only authenticated users are providers and admins, who log in through Internet Identity (ICP's privacy-preserving authentication system) to manage their own listings. Searches are anonymous: when someone searches for a provider by ZIP code, the system records only the ZIP code and a timestamp — never an IP address, never a device fingerprint, never a session ID that could be linked back to a person. The canister architecture on the Internet Computer Protocol means there is no central server to subpoena and no advertising SDK with access to query data.",
    "The clinical rationale for anonymity is grounded in barrier research. Treatment access studies consistently identify perceived confidentiality as one of the most significant factors in help-seeking behavior, particularly among populations with prior criminal justice involvement, parents who fear child protective services, and employed professionals who fear workplace consequences. A tool that requires account creation — even with strong privacy promises — creates a perceived barrier that a tool with zero account requirement does not. The absence of an account is not a technical limitation; it is the intentional design.",
    "Zero-PHI means more than legal compliance. HIPAA sets a floor, not a ceiling. Live Now Recovery's architecture goes beyond HIPAA requirements by design: we don't collect the data that HIPAA would require us to protect, because we never needed it in the first place. Provider listings contain logistics information only — name, location, availability status, provider type. No patient names, no diagnoses, no treatment history, no insurance information. The system is a supply-side directory, not a patient management system, and that distinction is fundamental to what makes it trustworthy for the communities it serves.",
  ],
  "economics-of-addiction": [
    "The economic barriers to addiction treatment are as lethal as the pharmacological ones. A patient with opioid use disorder who cannot afford $185 per month for their medication has effectively been denied treatment by the market. Generic buprenorphine/naloxone is not a patented specialty drug — it has been off-patent for years. The retail price is a markup artifact, not a reflection of production cost. Mark Cuban Cost Plus Drugs prices the same medication at $45.37 per month: $1.51 per film, with a $3 pharmacy dispensing fee. The gap between those prices is a systemic failure that a transparency intervention can partially close.",
    "The information gap compounds the price problem. In surveys of patients on buprenorphine, a substantial majority report that they were never told about lower-cost pharmacy options by their prescriber. The prescriber may not know, or may not consider it their responsibility, or may not have time. The result is that patients who could afford $45 per month are paying $185 because no one told them there was an alternative. This is not a minor inconvenience — for someone on disability income or working a service industry job, the $140 difference can determine whether they stay in treatment or drop out.",
    "Price transparency changes treatment outcomes. When patients can compare real costs and find affordable options, treatment retention improves. The evidence from pharmacy benefit research shows that even modest co-pay reductions significantly improve adherence for chronic disease medications, and buprenorphine behaves like other chronic disease medications in this respect. Live Now Recovery includes the Mark Cuban Cost Plus Drugs price comparison on every provider profile page because visibility of the price gap is the first step toward patients acting on it.",
    "The broader economics of addiction treatment illustrate why the cost transparency argument extends beyond individual patients. Every dollar invested in MAT yields an estimated $4 to $7 in reduced drug-related crime, criminal justice costs, and healthcare costs — and some estimates put the return higher when long-term productivity gains are included. The economic case for expanding access to affordable MAT is not a social justice argument dressed in numbers — it's a straightforward cost-benefit analysis. Solving the information and cost barriers is not charitable; it's fiscally rational. Live Now Recovery exists at the intersection of those two arguments.",
  ],
  "peer-support-specialists": [
    "Peer support specialists — also called peer recovery coaches, peer mentors, or certified peer supporters — are people with lived experience of addiction and recovery who are trained to support others navigating the same journey. What distinguishes them from clinical staff is not just their personal history but the quality of trust it creates. When someone in active addiction or early recovery meets a peer specialist, they are meeting someone who has been where they are, who speaks their language without clinical distance, and whose recovery is walking proof that the way out exists. That trust is clinically irreplaceable.",
    "The evidence base for peer support in addiction treatment has strengthened significantly over the past decade. Randomized controlled trials and observational studies consistently show that peer support interventions improve treatment engagement, reduce substance use, and improve quality of life outcomes. In emergency department settings, peer specialist interventions initiated at the point of an overdose — before discharge — produce treatment uptake rates that significantly exceed those of standard referral protocols. SAMHSA now recognizes peer support as an evidence-based practice and funds peer specialist certification programs through the Substance Abuse Prevention and Treatment Block Grant.",
    "In NE Ohio, peer specialists play a critical role in warm handoffs — the direct, real-time connections between people in crisis and MAT providers. A peer specialist stationed at an emergency department can initiate a buprenorphine conversation before a patient leaves, complete the connection to an outpatient prescriber while the patient is still in the room, and follow up by phone or text in the days after discharge to prevent the drop-off that makes early recovery so precarious. This workflow requires real-time information about provider availability — which is exactly the gap Live Now Recovery was built to close.",
    "Live Now Recovery was designed around the peer specialist workflow from the beginning. The system's core features — real-time provider status, anonymous search, one-tap calling, the Proof of Presence QR code system — were specified through conversations with peer recovery organizations in Cuyahoga and Lorain counties. The tool is useful to anyone searching for MAT access, but it is built to perform best in the hands of a trained peer specialist who knows how to use real-time availability data to complete a warm handoff at the exact moment someone is willing to accept help.",
  ],
};

export function BlogPostPage() {
  const params = useParams({ strict: false }) as { slug?: string };
  const slug = params.slug ?? "";
  const post = BLOG_POSTS.find((p) => p.slug === slug);
  const content = FULL_CONTENT[slug] ?? [];

  if (!post) {
    return (
      <div
        className="min-h-screen flex flex-col items-center justify-center gap-4"
        data-ocid="blog_post.error_state"
      >
        <p className="text-foreground font-semibold">Post not found</p>
        <Link to="/blog" className="text-primary hover:underline text-sm">
          ← Back to blog
        </Link>
      </div>
    );
  }

  return (
    <main className="min-h-screen bg-background" data-ocid="blog_post.page">
      {/* Dark hero header — double bg-navy wrapper prevents any parent color bleed */}
      <div className="bg-navy w-full">
        <section className="bg-navy px-4 py-14">
          <div className="max-w-2xl mx-auto">
            <Link
              to="/blog"
              className="inline-flex items-center gap-2 text-sm text-white/60 hover:text-white mb-6 transition-colors"
              data-ocid="blog_post.link"
            >
              <ArrowLeft className="w-4 h-4" /> Back to blog
            </Link>
            <div className="flex items-center gap-3 mb-4">
              <Badge className="bg-live-green/20 text-live-green border border-live-green/30 hover:bg-live-green/20 text-xs font-semibold">
                {post.category}
              </Badge>
              <div className="flex items-center gap-1 text-xs text-white/60">
                <Calendar className="w-3 h-3" />
                {post.date}
              </div>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-white leading-tight">
              {post.title}
            </h1>
          </div>
        </section>
      </div>

      <div className="max-w-2xl mx-auto px-4 py-12">
        <div className="prose prose-slate max-w-none">
          {content.length === 0 ? (
            <p className="text-muted-foreground leading-relaxed mb-5 text-base">
              {post.excerpt}
            </p>
          ) : (
            content.map((para) => (
              <p
                key={para.slice(0, 40)}
                className="text-muted-foreground leading-relaxed mb-5 text-base"
              >
                {para}
              </p>
            ))
          )}
        </div>
      </div>
    </main>
  );
}
