/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CanisterStateSummary {
  'active_providers' : Array<[string, bigint, boolean]>,
  'total_active_providers' : bigint,
  'high_risk_window_active' : boolean,
}
export type ProviderStatus = { 'Live' : null } |
  { 'Offline' : null } |
  { 'Unknown' : null };
export interface ProviderWithStatus {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'status' : ProviderStatus,
  'name' : string,
  'isLive' : boolean,
  'lastVerified' : bigint,
}
export interface RiskPacket {
  'status' : boolean,
  'data_source' : string,
  'last_update_time' : bigint,
  'provider_id' : string,
  'risk_score' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerifyResult = { 'Ok' : string } |
  { 'NotFound' : null } |
  { 'Expired' : null } |
  { 'AlreadyUsed' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateHandoffToken' : ActorMethod<[string], string>,
  'getAllProviders' : ActorMethod<[], Array<ProviderWithStatus>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterState' : ActorMethod<[], CanisterStateSummary>,
  'getEmergencyActive' : ActorMethod<[], Array<ProviderWithStatus>>,
  'getHandoffCountsByZip' : ActorMethod<[], Array<[string, bigint]>>,
  'getTotalHandoffs' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'heartbeat' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'receiveRiskPacket' : ActorMethod<[RiskPacket], undefined>,
  'registerProvider' : ActorMethod<[string, string, number, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLive' : ActorMethod<[string, boolean], undefined>,
  'verifyHandoff' : ActorMethod<[string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];