/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Helper = IDL.Record({
  'id' : IDL.Text,
  'zip' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ProviderStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Offline' : IDL.Null,
  'Unknown' : IDL.Null,
});
export const ProviderWithStatus = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : ProviderStatus,
  'name' : IDL.Text,
  'isLive' : IDL.Bool,
  'lastVerified' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CanisterStateSummary = IDL.Record({
  'active_providers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool)),
  'total_active_providers' : IDL.Nat,
  'high_risk_window_active' : IDL.Bool,
});
export const RiskPacket = IDL.Record({
  'status' : IDL.Bool,
  'data_source' : IDL.Text,
  'last_update_time' : IDL.Nat,
  'provider_id' : IDL.Text,
  'risk_score' : IDL.Nat,
});
export const VerifyResult = IDL.Variant({
  'Ok' : IDL.Text,
  'NotFound' : IDL.Null,
  'Expired' : IDL.Null,
  'AlreadyUsed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateHandoffToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllHelpers' : IDL.Func([], [IDL.Vec(Helper)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterState' : IDL.Func([], [CanisterStateSummary], ['query']),
  'getEmergencyActive' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
  'getHandoffCountsByZip' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTotalHandoffs' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'heartbeat' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveRiskPacket' : IDL.Func([RiskPacket], [], []),
  'registerHelper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'verifyHandoff' : IDL.Func([IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Helper = IDL.Record({
    'id' : IDL.Text,
    'zip' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ProviderStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Offline' : IDL.Null,
    'Unknown' : IDL.Null,
  });
  const ProviderWithStatus = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : ProviderStatus,
    'name' : IDL.Text,
    'isLive' : IDL.Bool,
    'lastVerified' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CanisterStateSummary = IDL.Record({
    'active_providers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Bool)),
    'total_active_providers' : IDL.Nat,
    'high_risk_window_active' : IDL.Bool,
  });
  const RiskPacket = IDL.Record({
    'status' : IDL.Bool,
    'data_source' : IDL.Text,
    'last_update_time' : IDL.Nat,
    'provider_id' : IDL.Text,
    'risk_score' : IDL.Nat,
  });
  const VerifyResult = IDL.Variant({
    'Ok' : IDL.Text,
    'NotFound' : IDL.Null,
    'Expired' : IDL.Null,
    'AlreadyUsed' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateHandoffToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllHelpers' : IDL.Func([], [IDL.Vec(Helper)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderWithStatus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterState' : IDL.Func([], [CanisterStateSummary], ['query']),
    'getEmergencyActive' : IDL.Func(
        [],
        [IDL.Vec(ProviderWithStatus)],
        ['query'],
      ),
    'getHandoffCountsByZip' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTotalHandoffs' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'heartbeat' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveRiskPacket' : IDL.Func([RiskPacket], [], []),
    'registerHelper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'verifyHandoff' : IDL.Func([IDL.Text], [VerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };